server:
  port: 9999

#配置数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    NAS数据库
    url: jdbc:mysql://192.168.100.10:23306/ldd_saas
    username: root
    password: yang517777346.

#    url: jdbc:mysql://192.168.3.23:3307/ldd_saas
#    username: root
#    password: My123456
    hikari:
      data-source-properties:
        serverTimezone: Asia/Shanghai
        characterEncoding: utf8
        useSSL: false





mybatis-plus:
  type-handlers-package: com.iooiee.**

logging:
  level:
    com.iooiee: debug